language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lagrange' ]; then cd .. && eval "mv $currentfolder generator-lagrange" && cd generator-lagrange; fi

